---
title: "clustering_trend_analysis"
author: "Farshad Ebrahimi"
date: '2023-08-21'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#create negate of %in%
`%!in%` = Negate(`%in%`)
```

## R Markdown to cluster the SMPs

```{r }
# Script to cluster the SMP population based on Loading ratio, location, type, age of system, Connected to surface SMP (Y/N)
# for stratified sampling. Goal is to develop a representative sample for the trend analysis.
# Author: Farshad Ebrahimi
# Last updated: 8/17/2023
# Project: Long-term trend analysis

# Libraries 
  library(odbc)
  library(ggplot2)
  library(stats)
  library(lubridate)
  library(DBI)
  library(tidyverse)
  library(data.table)
  library(stats) # kmeans clustering
  library(factoextra) 
  
# DB PG14
  con <- dbConnect(odbc::odbc(), dsn = "mars14_data", uid = Sys.getenv("shiny_uid"), pwd = Sys.getenv("shiny_pwd"), MaxLongVarcharSize = 8190)
  
  
 #db for SMP polygons
  gis_apps <- paste0("MSSQL:server=PWDGISSQL;",
                          "database=GIS_APPS;",
                          "UID=gisread;",
                          "PWD=gisread;")
  
  sysbdv <- dbGetQuery(con,"SELECT * FROM external.tbl_systembdv")
  smpbdv <- dbGetQuery(con,"SELECT * FROM external.tbl_smpbdv") %>%
    select(system_id, smp_pretreatment) %>%
    distinct()
  sys_gage <- dbGetQuery(con, "SELECT admin.fun_smp_to_system(smp_id) as system_id, gage_uid FROM admin.tbl_smp_gage") %>%
    distinct()
  project_bdv <- dbGetQuery(con, "SELECT * from external.tbl_projectbdv")
  cipit <- dbGetQuery(con, "SELECT * FROM  external.tbl_cipit_project")
  unmonitored_list <- dbGetQuery(con, "SELECT * FROM fieldwork.viw_unmonitored_postcon_on")
  
  


  # filter for categories relevant to the trend analysis
  
  sysbdv_ta <- sysbdv %>%
    filter(sys_modelinputcategory == "Subsurface slow release (unlined)" | sys_modelinputcategory == "Subsurface infiltration" | sys_modelinputcategory == "Bioinfiltration") %>%
    inner_join(cipit, by = "worknumber") 

    
  # construction_start_date field is the most complete column to use as a proxy of system age. To correct it, we subtract 1 from it to reflect the actual system age. 
  
  sysbdv_clustervar <- sysbdv_ta %>% 
    filter(!is.na(construction_start_date)) %>%
    mutate(sys_age_yr = as.numeric((Sys.Date() - construction_start_date)/365) - 1 ) %>%
    filter(sys_age_yr > 0 ) %>%
    filter(is.na(sys_notbuiltretired)) %>%
    select(system_id, sys_lrtotalda_ft2, sys_modelinputcategory, sys_age_yr) %>%
    inner_join(sys_gage, by = "system_id") 
  
  # Mutate the pretreatment type
  
  sysbdv_clustervar <- sysbdv_clustervar %>%
    inner_join(smpbdv, by = "system_id")
    
  
  # Filter for upstream smp
  output <- sysbdv_clustervar[sysbdv_clustervar$smp_pretreatment %like% "Upstream SMP", ]
  
  # Make the upstream smp pretreatment binary (1 for presence)
  sysbdv_clustervar <- sysbdv_clustervar %>%
    mutate(smp_pretreatment = case_when(system_id %in% output$system_id ~ 1,
                                        system_id %!in% output$system_id ~ 0))
      

```

After preparing the variables, we need to scale the them, find the optimum number of clusters and perform clustering using kmeans function from the stats package.

```{r}
# scale numeric columns
sysbdv_df <- sysbdv_clustervar
sysbdv_clustervar[,c(2,4)] <- scale(sysbdv_clustervar[,c(2,4)])
sysbdv_clustervar <- na.omit(sysbdv_clustervar)



#Elbow method
#number of clusters
elbow_lined_fig <- fviz_nbclust(sysbdv_clustervar[,c(2,4,6)], kmeans, method = "wss")

cluster_solution <- kmeans(sysbdv_clustervar[,c(2,4,6)], centers = 2)

# Store the cluster assignments back into the clustering data frame object
sysbdv_df$cluster <-factor(cluster_solution$cluster) 

# Look at the distribution of cluster assignments
table(sysbdv_df$cluster)


```

```{r}

stratified_sample_0.1 <- sysbdv_df %>%
     group_by(sys_modelinputcategory, cluster, gage_uid) %>%
     sample_frac(size= 0.1)

```
